services:
  smartdoor-mongodb:
    container_name: smartdoor-mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - smartdoor-networks

  smartdoor-mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - smartdoor-mongodb  
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@smartdoor-mongodb:27017
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    networks:
      - smartdoor-networks

  smartdoor-server:
    container_name: smartdoor-server
    image: ${REGISTRY_USERNAME}/smartdoor-server:latest
    depends_on:
      - smartdoor-mongodb 
    restart: always
    ports:
      - 10000:10000
    build:
      context: smartdoor-server
      dockerfile: Dockerfile
    environment:
      PORT: 10000
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@smartdoor-mongodb:27017/${DB_NAME}?authSource=admin
    networks:
      - smartdoor-networks

  smartdoor-client:
    container_name: smartdoor-client
    image: ${REGISTRY_USERNAME}/smartdoor-client:latest
    ports:
      - 10100:3000
    restart: always
    build:
      context: smartdoor-client
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
    networks:
      - smartdoor-networks

networks:
  smartdoor-networks:
    name: smartdoor_networks
      
