on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      API_BASE_URL: ${{secrets.API_BASE_URL}}
      REGISTRY_USERNAME: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker compose build smartdoor-server smartdoor-client --no-cache
          docker compose push

  deploy-application:
    runs-on: self-hosted
    needs: build-image
    env:
      REGISTRY_USERNAME: ghcr.io/${{ github.repository }}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      MONGO_EXPRESS_USER: ${{secrets.MONGO_EXPRESS_USER}}
      MONGO_EXPRESS_PASSWORD: ${{secrets.MONGO_EXPRESS_PASSWORD}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      DB_NAME: ${{secrets.DB_NAME}}
      HMAC_SECRET_KEY: ${{secrets.HMAC_SECRET_KEY}}
      FRONTEND_URL: ${{secrets.FRONTEND_URL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker compose -p smarthome-application down smartdoor-server smartdoor-client --rmi all -v
          docker compose -p smarthome-application up -d
